### ISSUE TITLE
NSP version - In which directory for usage in Atmosphere?

### ISSUE THREAD

**Issue by OperationNT414C** [jakibaki/sys-ftpd#20]
Hello,

Since the latest commit "go back to pm loading", there is an NSP file generated instead of a KIP file. To use this plugin, I put it inside "SDCard:/atmosphere/kips" directory. But with NSP file, I am a little bit lost: where shoud I put "sys-ftpd.nsp" to get it work?

Thank you for your help!

**Comment by friedkeenan** [comment]
Per [switchbrew's instructions](https://github.com/switchbrew/switch-examples/blob/master/templates/sysmodule/README.md), you would rename the output NSP to `exefs.nsp`, then make a folder in `sdmc:/atmosphere/titles/` called `420000000000000E`, put the NSP in that folder, create the folder `flags` inside that folder, and put an empty file called `boot2.flag` inside the `flags` folder.

If you find that process a little tedious, you can always just grab the kip from [Kosmos](https://github.com/AtlasNX/Kosmos/raw/master/Modules/sys-ftpd/modules/sysftpd/sys-ftpd.kip), as nothing has been added since switching to PM loading

**Comment by OperationNT414C** [comment]
Thank you for the explanations and the link to the documentation! I was looking at Atmosphere github but never find a clear answer.
In fact, I want to try to generate myself the latest version because the previous version I was using (in ".kip" form) was crashing when it was used with "ldn_mitn_v*.kip" plugin (https://github.com/spacemeowx2/ldn_mitm/releases/).
With the version I generated (NSP output), both plugins used at the same time seem to work fine (at least, it doesn't make Atmosphere crash on boot).
