### ISSUE TITLE
Incredibly slow transfer speeds compared to regular ftpd

### ISSUE THREAD

**Issue by thedax** [jakibaki/sys-ftpd#6]
I'm on firmware 5.1 running hekate 3.2, and I'm getting upload/download speeds of around 150 KBytes/sec, whereas https://github.com/WinterMute/ftpd/releases/tag/v2.2.0-e627691c-switch is getting around 3-5 MBytes/sec.

It's a shame since this is much more stable than the regular ftpd (that always crashes after around 30 seconds of transferring anything large (say 300mb or more)).

**Comment by jakibaki** [comment]
yeah, that's a known problem.

Because of the very limited ram-pool for sysmodules (most of which was used by layeredfs) the socket-buffers had to be decreased by a large amount.

This will change as soon as the atmosphere-pm lands in the sdfiles since that enables me to get more memory and thus bigger buffers for ftpd again :)

**Comment by jakibaki** [comment]
Solved with #7 !

**Comment by thedax** [comment]
Thanks! It's still pretty slow (500 KBytes/sec), but much better than before. Hopefully someday it'll match full-on ftpd.
